export const VideoActionTypes = {
  FETCH_VIDEOS_START: 'FETCH_VIDEOS_START',
  FETCH_VIDEOS_SUCCESS: 'FETCH_VIDEOS_SUCCESS',
  FETCH_VIDEOS_FAILURE: 'FETCH_VIDEOS_FAILURE',
  FILTER_VIDEOS_TAGS: 'FILTER_VIDEOS_TAGS'
}